version: "3"
services:
  # my-app:
  #   build:
  #     context: .
  #   depends_on:
  #     - postgres
  #   env-file:
  #     ./dev.ev
  #   ports:
  #     - "5000:5000"
  #   restart: always

  db:
    container_name: bakir_database
    image: postgres
    ports:
      - "3010:5432"
    restart: always
    environment:
      - "POSTGRES_USER=userw"
      - "POSTGRES_PASSWORD=password_123"
      - "POSTGRES_DB=bakir_db"

