version: "3"
services:
  db:
    container_name: bakir_database
    image: postgres
    ports:
      - "3010:5432"
    restart: always
    environment:
      - "POSTGRES_USER=userw"
      - "POSTGRES_PASSWORD=password_123"
      - "POSTGRES_DB=bakir_db"

